name: .NET Core

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build_server:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Server
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build Server
      run: dotnet build --configuration Release --no-restore
    - name: Test Server
      run: dotnet test --no-restore --verbosity normal

  build_client:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: Client
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build Client
      run: dotnet build --configuration Release --no-restore
    - name: Test Client
      run: dotnet test --no-restore --verbosity normal
